/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
//Basic includes
#include "stm32wlxx.h"
#include "stm32wlxx_hal_conf.h"
#include "stm32wlxx_hal.h"
#include "stm32wlxx_hal_gpio.h"
#include "stm32wlxx_hal_rcc.h"
#include "stm32wlxx_hal_pwr.h"
#include "stm32wlxx_hal_pwr_ex.h"

#include <stdio.h>

#include "rfl_clocks.h"
#include "rfl_usart.h"
#include "rfl_gpio.h"

#include "hal_based_subghz.h"

void Debbug_Toggle(uint32_t cycles){
    for(uint32_t i = 0; i < cycles; i++)
        __NOP(); // no operations

    led_state(toggle);
}

int main(void){
	HAL_Init();

	//Clock init
//	HSI16_init();
	HSI_PLL48_init();
//	HSE32_CPU_init();

	//Green led init
	led_init();

	//USART init
	USART1_Init(); //115200
	printf("System start - usart init check\r\n");

	//Radio init
	subghz_init();
	subghz_init_rx();
//	subghz_init_tx();

	while(1){
		Debbug_Toggle(1000000);
	}


}

